version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
      - media:/app/media/
    env_file:
      - .env

  backend:
    build: ./backend/
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - static:/backend_static/
      - media:/app/media/

  frontend:
    env_file:
      - .env
    build: ./frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
      - media:/app/media/

  gateway:
    build: ./nginx/
    depends_on:
      - backend
    env_file:
      - .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles
      - media:/media/
